name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: DockerHub Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Pull Docker image
        run: sudo docker pull souvik150/trademarkia:latest

      - name: Delete old Docker container
        run: sudo docker rm -f trademarkia || true

      - name: Run Docker container
        run: sudo docker run -d -p 8080:8080 --name trademarkia souvik150/trademarkia:latest
