name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22

          script: |
            # Navigate to the project directory
            cd ~/21BCE0021_Backend

            # Pull the latest code
            git pull origin main

            # Build the Docker image
            docker build -t trademarkia:latest .

            # Stop the running container (if exists)
            docker stop trademarkia || true
            docker rm trademarkia || true

            # Run the container in detached mode on port 8080
            docker run -d -p 8080:8080 --name trademarkia trademarkia:latest
